apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/muhammadnkhan/eks-cluster-tier1-workloads.git//workload-A/overlays/prod?ref=main

commonLabels:
  cluster: my-cluster

