apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
metadata:
  name: eks-cluster-tier-1
resources:
  # “remote-base” from the eks-cluster-tier1-workloads repo:
  - https://github.com/muhammadnkhan/eks-cluster-tier1-workloads.git//workload-1/overlays/prod?ref=main

commonLabels:
  cluster: eks-cluster-tier-1


